name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew test jacocoTestReport generateCoverageBadge
      - name: Update coverage badge
        uses: mshick/add-pr-comment@v2
        if: github.event_name == 'pull_request'
        with:
          message: |
            Coverage report: [HTML Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            ![Coverage](https://img.shields.io/badge/coverage-$(cat coverage.json | jq -r .message)-$(cat coverage.json | jq -r .color))
      - name: Commit coverage badge
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add coverage.json
          git commit -m "Update coverage badge"
          git push 